# src/gan/evaluate_gan.py
"""
GAN Evaluation Script
====================

Evaluate synthetic images generated by GAN using:
- FID (Fréchet Inception Distance)
- Per class
- Per GAN experiment

Windows-safe version:
- Use hardlink if possible
- Fallback to file copy
- Auto cleanup temp data

Author: DermGAN_Classification
"""

import sys
import shutil
import subprocess
import json
import os
from pathlib import Path
from typing import Dict, List

import yaml
import pandas as pd
from tqdm import tqdm
import torch


# ======================================================
# Project root
# ======================================================
PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT))


# ======================================================
# Utils
# ======================================================
def load_yaml(path: Path) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def run_fid(real_dir: Path, fake_dir: Path, device: str) -> float:
    """
    Run FID using pytorch-fid with the SAME python executable (venv-safe)
    """
    cmd = [
        sys.executable,          
        "-m",
        "pytorch_fid",
        str(real_dir),
        str(fake_dir),
        "--device",
        device,
    ]

    result = subprocess.run(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )

    if result.returncode != 0:
        raise RuntimeError(
            "[FID ERROR]\n"
            f"CMD: {' '.join(cmd)}\n\n"
            f"STDOUT:\n{result.stdout}\n\n"
            f"STDERR:\n{result.stderr}"
        )

    for line in result.stdout.splitlines():
        if "FID" in line:
            return float(line.split()[-1])

    raise RuntimeError("[FID ERROR] Could not parse FID score")



def safe_link_or_copy(src: Path, dst: Path):
    """
    Windows-safe linking:
    1. Try hard link
    2. Fallback to copy
    """
    try:
        os.link(src, dst)
    except Exception:
        shutil.copy2(src, dst)


def prepare_real_images(
    train_df: pd.DataFrame,
    label: str,
    real_image_root: Path,
    tmp_real_dir: Path,
) -> int:
    """
    Prepare real images for one class into temp folder.
    """
    cls_df = train_df[train_df["dx"] == label]

    if cls_df.empty:
        return 0

    tmp_real_dir.mkdir(parents=True, exist_ok=True)

    for _, row in cls_df.iterrows():
        img_name = row["image_id"] + ".jpg"
        src = real_image_root / img_name
        dst = tmp_real_dir / img_name

        if src.exists() and not dst.exists():
            safe_link_or_copy(src, dst)

    return len(cls_df)


# ======================================================
# Main
# ======================================================
def main():
    # --------------------------------------------------
    # Load config
    # --------------------------------------------------
    gan_cfg = load_yaml(PROJECT_ROOT / "configs" / "gan.yaml")["gan"]
    experiment = gan_cfg["experiment_name"]

    # --------------------------------------------------
    # Paths
    # --------------------------------------------------
    syn_meta_path = (
        PROJECT_ROOT / "dataset" / "synthetic" / gan_cfg["generation"]["metadata"]
    )
    train_csv = PROJECT_ROOT / "dataset" / "splits" / "train.csv"
    real_image_root = PROJECT_ROOT / "dataset" / "processed" / "train"
    synthetic_root = PROJECT_ROOT / gan_cfg["generation"]["output_dir"] 

    eval_root = (
        PROJECT_ROOT
        / gan_cfg["results"]["root"]
        / "gan"
        / gan_cfg["results"]["evaluate"]
    )
    eval_root.mkdir(parents=True, exist_ok=True)

    fid_csv_path = eval_root / gan_cfg["results"]["fid_csv"]
    fid_json_path = eval_root / gan_cfg["results"]["fid_json"]

    tmp_real_root = eval_root / "_tmp_real"
    tmp_real_root.mkdir(exist_ok=True)

    # --------------------------------------------------
    # Device
    # --------------------------------------------------
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"[Device] {device}")

    # --------------------------------------------------
    # Load CSVs
    # --------------------------------------------------
    print("[INFO] Loading train split CSV...")
    train_df = pd.read_csv(train_csv)

    print("[INFO] Loading synthetic metadata...")
    meta = pd.read_csv(syn_meta_path)

    # --------------------------------------------------
    # Group by class
    # --------------------------------------------------
    grouped = meta.groupby("label")
    print(f"[INFO] Found {len(grouped)} classes to evaluate")

    results: List[Dict] = []

    # --------------------------------------------------
    # Evaluate
    # --------------------------------------------------
    for label, group in tqdm(grouped, desc="Evaluating GAN"):
        fake_dir = synthetic_root / label
        real_tmp_dir = tmp_real_root / label

        if not fake_dir.exists():
            print(f"[WARN] Missing synthetic dir: {fake_dir}")
            continue

        n_real = prepare_real_images(
            train_df=train_df,
            label=label,
            real_image_root=real_image_root,
            tmp_real_dir=real_tmp_dir,
        )

        if n_real == 0:
            print(f"[WARN] No real images for class {label}")
            continue

        n_fake = len(list(fake_dir.glob("*")))

        print(f"\n[GAN EVAL]")
        print(f"  Class       : {label}")
        print(f"  Real images : {n_real}")
        print(f"  Fake images : {n_fake}")

        fid = run_fid(real_tmp_dir, fake_dir, device)

        results.append({
            "label": label,
            "gan_experiment": experiment,
            "fid": float(fid),
            "real_count": int(group["real_count"].iloc[0]),
            "target_count": int(group["target_count"].iloc[0]),
            "num_generated": n_fake,
        })

        print(f"  → FID = {fid:.3f}")

    # --------------------------------------------------
    # Save results
    # --------------------------------------------------
    df = pd.DataFrame(results)
    df.to_csv(fid_csv_path, index=False)

    with open(fid_json_path, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2)

    shutil.rmtree(tmp_real_root, ignore_errors=True)

    print("\n[SUCCESS] GAN evaluation completed")
    print(f"[SAVED] {fid_csv_path}")
    print(f"[SAVED] {fid_json_path}")


if __name__ == "__main__":
    main()
